### ISSUE TITLE
Partially initialized module 'robosuite' has no attribute 'make' 

### ISSUE THREAD

**Issue by sambaPython24** [ARISE-Initiative/robosuite#410]
When trying to run ```python -m robosuite.demos.demo_random_action``` or when I try to run the example script
```
import numpy as np
import robosuite as suite

# create environment instance
env = suite.make(
    env_name="Lift", # try with other tasks like "Stack" and "Door"
    robots="Panda",  # try with other robots like "Sawyer" and "Jaco"
    has_renderer=True,
    has_offscreen_renderer=False,
    use_camera_obs=False,
)

# reset the environment
env.reset()

for i in range(1000):
    action = np.random.randn(env.robots[0].dof) # sample random action
    obs, reward, done, info = env.step(action)  # take action in the environment
    env.render()  # render on display
```

I get the error 

```
Traceback (most recent call last):
  File ".../anaconda3/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "../anaconda3/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "path_to_script/robosuite.py", line 5, in <module>
    env = suite.make(
AttributeError: partially initialized module 'robosuite' has no attribute 'make' (most likely due to a circular import)
```

**Comment by zxfever** [comment]
@sambaPython24 The same error, have you solved it?

**Comment by InfiniteLoopCoder** [comment]
replace robosuite.make with robosuite.environments.base.make can mostly solve the problem

> [@sambaPython24](https://github.com/sambaPython24) The same error, have you solved it?
