### ISSUE TITLE
test grippers import bug

### ISSUE THREAD

**Issue by kingduyin** [ARISE-Initiative/robosuite#477]
## error msg:

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../robosuite/tests/test_grippers/test_robotiq_85.py", line 25, in <module>
    robotiq_tester(True, 20, False)
  File ".../robosuite/tests/test_grippers/test_robotiq_85.py", line 19, in robotiq_tester
    tester.start_simulation()
  File ".../robosuite/robosuite/models/grippers/gripper_tester.py", line 122, in start_simulation
    render_context = MjRenderContextOffscreen(self.sim, device_id=-1)
NameError: name 'MjRenderContextOffscreen' is not defined
```

## fix bug: 
'robosuite/models/grippers/gripper_tester.py' File add  'from robosuite.utils.binding_utils import MjRenderContextOffscreen'

**Comment by kevin-thankyou-lin** [comment]
Should be fixed in latest release (currently in [branch](https://github.com/ARISE-Initiative/robosuite/tree/v1.5.0))
