### ISSUE TITLE
Install Error: Cannot initialize a EGL device display.

### ISSUE THREAD

**Issue by GuHuangAI** [ARISE-Initiative/robosuite#490]
I would like to record the issue when installing the environment and how to solve it.

**Comment by GuHuangAI** [comment]
Environment:
Ubuntu22.04
RTX 4090
CUDA11.7
DRIVER:525.89.02

**Comment by GuHuangAI** [comment]
After I installed the packages of requirements.txt, I ran the command `python robosuite/demos/demo_random_action.py`. However, it failed:
`ImportError: Cannot initialize a EGL device display. This likely means that your EGL driver does not support the PLATFORM_DEVICE extension, which is required for creating a headless rendering context.`

**Comment by GuHuangAI** [comment]
However, it led to another error:
`libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
/home/huang/anaconda3/envs/robosuite/lib/python3.8/site-packages/glfw/__init__.py:914: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "robosuite/demos/demo_random_action.py", line 45, in <module>
    env = suite.make(
  File "/home/huang/code/robosuite-master/robosuite/environments/base.py", line 40, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/huang/code/robosuite-master/robosuite/environments/manipulation/door.py", line 178, in __init__
    super().__init__(
  File "/home/huang/code/robosuite-master/robosuite/environments/manipulation/manipulation_env.py", line 162, in __init__
    super().__init__(
  File "/home/huang/code/robosuite-master/robosuite/environments/robot_env.py", line 214, in __init__
    super().__init__(
  File "/home/huang/code/robosuite-master/robosuite/environments/base.py", line 143, in __init__
    self._reset_internal()
  File "/home/huang/code/robosuite-master/robosuite/environments/manipulation/door.py", line 401, in _reset_internal
    super()._reset_internal()
  File "/home/huang/code/robosuite-master/robosuite/environments/robot_env.py", line 510, in _reset_internal
    super()._reset_internal()
  File "/home/huang/code/robosuite-master/robosuite/environments/base.py", line 299, in _reset_internal
    render_context = MjRenderContextOffscreen(self.sim, device_id=self.render_gpu_device_id)
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 211, in __init__
    super().__init__(sim, offscreen=True, device_id=device_id, max_width=max_width, max_height=max_height)
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 110, in __init__
    self._set_mujoco_context_and_buffers()
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 113, in _set_mujoco_context_and_buffers
    self.con = mujoco.MjrContext(self.model._model, mujoco.mjtFontScale.mjFONTSCALE_150)
mujoco.FatalError: gladLoadGL error
Exception ignored in: <function MjRenderContext.__del__ at 0x7f98648ffaf0>
Traceback (most recent call last):
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 199, in __del__
AttributeError: 'MjRenderContextOffscreen' object has no attribute 'con'`

**Comment by GuHuangAI** [comment]
I found this error is caused by that the file `/usr/lib/dri/swrast_dri.so` was not exist.
But in fact, there is a file named `swrast_dri.so` in the directory `/usr/lib/x86_64-linux-gnu/dri/`.
So we need to create a soft link:
`sudo mkdir /usr/lib/dri`
`cd /usr/lib/dri`
`sudo ln -s  /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so swrast_dri.so`

**Comment by GuHuangAI** [comment]
Unfortunately, It was not done.
`libGL error: MESA-LOADER: failed to open swrast: /home/huang/anaconda3/envs/robosuite/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libLLVM-15.so.1) (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
/home/huang/anaconda3/envs/robosuite/lib/python3.8/site-packages/glfw/__init__.py:914: GLFWError: (65543) b'GLX: Failed to create context: BadValue (integer parameter out of range for operation)'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "robosuite/demos/demo_random_action.py", line 45, in <module>
    env = suite.make(
  File "/home/huang/code/robosuite-master/robosuite/environments/base.py", line 40, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
  File "/home/huang/code/robosuite-master/robosuite/environments/manipulation/door.py", line 178, in __init__
    super().__init__(
  File "/home/huang/code/robosuite-master/robosuite/environments/manipulation/manipulation_env.py", line 162, in __init__
    super().__init__(
  File "/home/huang/code/robosuite-master/robosuite/environments/robot_env.py", line 214, in __init__
    super().__init__(
  File "/home/huang/code/robosuite-master/robosuite/environments/base.py", line 143, in __init__
    self._reset_internal()
  File "/home/huang/code/robosuite-master/robosuite/environments/manipulation/door.py", line 401, in _reset_internal
    super()._reset_internal()
  File "/home/huang/code/robosuite-master/robosuite/environments/robot_env.py", line 510, in _reset_internal
    super()._reset_internal()
  File "/home/huang/code/robosuite-master/robosuite/environments/base.py", line 299, in _reset_internal
    render_context = MjRenderContextOffscreen(self.sim, device_id=self.render_gpu_device_id)
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 211, in __init__
    super().__init__(sim, offscreen=True, device_id=device_id, max_width=max_width, max_height=max_height)
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 110, in __init__
    self._set_mujoco_context_and_buffers()
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 113, in _set_mujoco_context_and_buffers
    self.con = mujoco.MjrContext(self.model._model, mujoco.mjtFontScale.mjFONTSCALE_150)
mujoco.FatalError: gladLoadGL error
Exception ignored in: <function MjRenderContext.__del__ at 0x7fc655100af0>
Traceback (most recent call last):
  File "/home/huang/code/robosuite-master/robosuite/utils/binding_utils.py", line 199, in __del__
AttributeError: 'MjRenderContextOffscreen' object has no attribute 'con'`

**Comment by GuHuangAI** [comment]
We found the key point: `version 'GLIBCXX_3.4.30' not found`.
To solve it, we would run the command `conda install -c conda-forge gcc`.
Finally done.
Hope can help anyone.

**Comment by kevin-thankyou-lin** [comment]
Thank you!

**Comment by jasonjabbour** [comment]
`conda install -c conda-forge gcc` worked for me, thanks!

**Comment by zhouyuchenzyccccc** [comment]
# New Error After Installing GCC & Final Solution
After running the command `conda install -c conda-forge gcc`, I encountered a new error as shown below:

```
Traceback (most recent call last):
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/ObjectFlow/experiments/robot/libero/regenerate_libero_dataset.py", line 470, in <module>
    main(args)
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/ObjectFlow/experiments/robot/libero/regenerate_libero_dataset.py", line 287, in main
    env, task_description = get_libero_env(task, "llava", resolution=IMAGE_RESOLUTION)
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/ObjectFlow/experiments/robot/libero/libero_utils.py", line 23, in get_libero_env
    env = OffScreenRenderEnv(**env_args)
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/LIBERO/libero/libero/envs/env_wrapper.py", line 161, in __init__
    super().__init__(**kwargs)
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/LIBERO/libero/libero/envs/env_wrapper.py", line 56, in __init__
    self.env = TASK_MAPPING[self.problem_name](
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/LIBERO/libero/libero/envs/problems/libero_floor_manipulation.py", line 37, in __init__
    super().__init__(bddl_file_name, *args, **kwargs)
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/LIBERO/libero/libero/envs/bddl_base_domain.py", line 135, in __init__
    super().__init__(
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/environments/manipulation/manipulation_env.py", line 162, in __init__
    super().__init__(
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/environments/robot_env.py", line 214, in __init__
    super().__init__(
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/environments/base.py", line 143, in __init__
    self._reset_internal()
  File "/inspire/hdd/project/wuliqifa/chenxinyan-240108120066/zhouyuchen/LIBERO/libero/libero/envs/bddl_base_domain.py", line 735, in _reset_internal
    super()._reset_internal()
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/environments/robot_env.py", line 510, in _reset_internal
    super()._reset_internal()
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/environments/base.py", line 299, in _reset_internal
    render_context = MjRenderContextOffscreen(self.sim, device_id=self.render_gpu_device_id)
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/utils/binding_utils.py", line 210, in __init__
    super().__init__(sim, offscreen=True, device_id=device_id, max_width=max_width, max_height=max_height)
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/utils/binding_utils.py", line 109, in __init__
    self._set_mujoco_context_and_buffers()
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/utils/binding_utils.py", line 112, in _set_mujoco_context_and_buffers
    self.con = mujoco.MjrContext(self.model._model, mujoco.mjtFontScale.mjFONTSCALE_150)
mujoco.FatalError: gladLoadGL error
Exception ignored in: <function MjRenderContext.__del__ at 0x7f9dca741630>
Traceback (most recent call last):
  File "/opt/conda/envs/openvla-oft/lib/python3.10/site-packages/robosuite/utils/binding_utils.py", line 198, in __del__
AttributeError: 'MjRenderContextOffscreen' object has no attribute 'con'
```

I fixed the problem by running the following commands in succession:
```bash
apt-get install xvfb
Xvfb :1 -screen 0 1920x1080x24 &
export DISPLAY=:1
```

I had been stuck with this issue for two days, and consulting GPT didn't help me resolve it at all. I finally got it fixed after seeing your answer. Thank you so much!!!

**Comment by artpli** [comment]
Just wanted to say, it worked after running all the fixes above. Thank you all!

**Comment by Luffy966** [comment]
# Another Solution of Using EGL directly
I'd like to share how I fix this issue by using EGL directly.

At the beginning, I met the same issue: `ImportError: Cannot initialize a EGL device display. This likely means that your EGL driver does not support the PLATFORM_DEVICE extension, which is required for creating a headless rendering context.` 
Besides, `MUJOCO_GL=glx/osmesa/glfw` are all failed with `mujoco.FatalError: gladLoadGL error`.

I carefully check my machine and discover that:
```shell
$ find /usr -name libEGL_nvidia.so* # outputs nothing.
$ ls /usr/share/glvnd/egl_vendor.d/
50_mesa.json
```
1. `libEGL_nvidia.so*` files are not in `/usr` or `/lib`
2. and `10_nvidia.json` is not in `/usr/share/glvnd/egl_vendor.d/`


After I run `sudo apt install libnvidia-gl-570-server`, then I found those files are supplemented:
```shell
$ find /usr -name libEGL_nvidia.so*
/usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0
/usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.570.133.20
$ ls /usr/share/glvnd/egl_vendor.d/
10_nvidia.json  50_mesa.json
```
and the issue is solved finally.

NOTE: `570` in `sudo apt install libnvidia-gl-570-server` should be placed by your own NVIDIA DRIVER version.

My Environment:
Ubuntu20.04
8*RTX 4090
CUDA11.8
DRIVER:570.133.20
