### ISSUE TITLE
EGL context is freed twice

### ISSUE THREAD

**Issue by MasonJohnHawver42** [ARISE-Initiative/robosuite#521]
### System Info

```Shell
OS Ubuntu 22.04.4 LTS x86_64 
robosuite 1.4.1
robomimic 0.3.0

pip list:
Package                 Version          Editable project location
----------------------- ---------------- -------------------------
absl-py                 2.1.0
Brotli                  1.1.0
cachetools              5.5.0
certifi                 2024.8.30
cffi                    1.17.0
charset-normalizer      3.3.2
click                   8.1.7
contourpy               1.1.1
cycler                  0.12.1
docker-pycreds          0.4.0
egl_probe               1.0.2
etils                   1.3.0
evdev                   1.7.1
filelock                3.16.1
fonttools               4.54.1
gitdb                   4.0.11
GitPython               3.1.43
glfw                    2.7.0
gmpy2                   2.1.5
google-auth             2.35.0
google-auth-oauthlib    1.0.0
grpcio                  1.66.2
h2                      4.1.0
h5py                    3.11.0
hpack                   4.0.0
hyperframe              6.0.1
idna                    3.10
imageio                 2.35.1
imageio-ffmpeg          0.5.1
importlib_metadata      8.5.0
importlib_resources     6.4.5
Jinja2                  3.1.4
kiwisolver              1.4.7
llvmlite                0.41.1
Markdown                3.7
MarkupSafe              2.1.5
matplotlib              3.7.5
mpmath                  1.3.0
mujoco                  3.2.3
networkx                3.1
numba                   0.58.1
numpy                   1.24.4
oauthlib                3.2.2
opencv-python           4.10.0.84
packaging               24.1
Pillow                  10.0.1
pip                     24.2
platformdirs            4.3.6
protobuf                5.28.2
psutil                  6.0.0
pyasn1                  0.6.1
pyasn1_modules          0.4.1
pycparser               2.22
pynput                  1.7.7
PyOpenGL                3.1.7
PyOpenGL-accelerate     3.1.7
pyparsing               3.1.4
PySocks                 1.7.1
python-dateutil         2.9.0.post0
python-xlib             0.33
PyYAML                  6.0.2
requests                2.32.3
requests-oauthlib       2.0.0
robomimic               0.3.0            /home/xxs/mjh/robomimic
robosuite               1.4.1            /home/xxs/mjh/robosuite
rsa                     4.9
scipy                   1.10.1
sentry-sdk              2.15.0
setproctitle            1.3.3
setuptools              75.1.0
six                     1.16.0
smmap                   5.0.1
sympy                   1.13.3
tensorboard             2.14.0
tensorboard-data-server 0.7.2
tensorboardX            2.6.2.2
termcolor               2.4.0
torch                   2.0.0.post304
torchvision             0.15.1a0+60a3e72
tqdm                    4.66.5
typing_extensions       4.12.2
urllib3                 2.2.3
wandb                   0.18.2
Werkzeug                3.0.4
wheel                   0.44.0
zipp                    3.20.2
zstandard               0.23.0
```

### Information

``` 
python robomimic/scripts/playback_dataset.py --dataset can/ph/demo_v141.hdf5 --render_image_names agentview robot0_eye_in_hand --video_path /tmp/playback_dataset.mp4 --n 2
```

### Reproduction

Run the following robomimic script and after it completes an error is thrown where the egl ctx is freed when it is not initialized.
This is the error experienced:
```
Exception ignored in: <function MjRenderContext.__del__ at 0x755621308040>
Traceback (most recent call last):
  File "/home/xxs/mjh/robosuite/robosuite/utils/binding_utils.py", line 199, in __del__
    self.gl_ctx.free()
  File "/home/xxs/mjh/robosuite/robosuite/renderers/context/egl_context.py", line 151, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglMakeCurrent,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7556082d59c0>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x75562140a340>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x75562140a340>,
		<OpenGL._opaque.EGLContext_pointer object at 0x75562140a7c0>,
	),
	result = 0
)
Exception ignored in: <function EGLGLContext.__del__ at 0x755621326e50>
Traceback (most recent call last):
  File "/home/xxs/mjh/robosuite/robosuite/renderers/context/egl_context.py", line 159, in __del__
    self.free()
  File "/home/xxs/mjh/robosuite/robosuite/renderers/context/egl_context.py", line 151, in free
    EGL.eglMakeCurrent(EGL_DISPLAY, EGL.EGL_NO_SURFACE, EGL.EGL_NO_SURFACE, EGL.EGL_NO_CONTEXT)
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglMakeCurrent,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7556082d59c0>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x75562140a340>,
		<OpenGL._opaque.EGLSurface_pointer object at 0x75562140a340>,
		<OpenGL._opaque.EGLContext_pointer object at 0x75562140a7c0>,
	),
	result = 0
)
```

### Expected behavior

No error

**Comment by snasiriany** [comment]
Issue was also raised here: https://github.com/ARISE-Initiative/robomimic/issues/166

We believe this is harmless and can be ignored.

However, let us know if you have a solution!
