### ISSUE TITLE
Demo scripts bugs

### ISSUE THREAD

**Issue by youliangtan** [ARISE-Initiative/robosuite#534]
### System Info

```Shell
v1.5
```

### Information

Bug tracker for demo scripts

### Reproduction

1. `python robosuite/demos/demo_control.py`

```sh
Choose a controller for the robot (enter a number from 0 to 4): 3
Traceback (most recent call last):
  File "/home/youliang/robosuite-dev/robosuite/demos/demo_control.py", line 95, in <module>
    options["controller_configs"] = suite.load_part_controller_config(default_controller=controller_name)
  File "/home/youliang/robosuite-dev/robosuite/controllers/parts/controller_factory.py", line 48, in load_part_controller_config
    default_controller in ALL_PART_CONTROLLERS
AssertionError: Error: Unknown default controller specified. Requested WHOLE_BODY_IK, available controllers: ['JOINT_VELOCITY', 'JOINT_TORQUE', 'JOINT_POSITION', 'OSC_POSITION', 'OSC_POSE', 'IK_POSE']
(robosuite-dev) youliang@youliang-Precision-5690:~/robosuite-dev$ 
```

also reported here https://github.com/ARISE-Initiative/robosuite/issues/532

2. `python robosuite/demos/demo_domain_randomization.py`
```sh
  File "/home/youliang/robosuite-dev/robosuite/utils/mjmod.py", line 866, in <listcomp>
    self.textures = [Texture(self.model, i) for i in range(self.model.ntex)]
  File "/home/youliang/robosuite-dev/robosuite/utils/mjmod.py", line 1390, in __init__
    self.tex_rgb = model.tex_rgb
AttributeError: 'MjModel' object has no attribute 'tex_rgb'. Did you mean: 'flex_rgba'?
```

3. `python robosuite/scripts/tune_joints.py`
```
  File "/home/youliang/robosuite_models/../robosuite-dev/robosuite/scripts/tune_joints.py", line 285, in <module>
    controller_config = robosuite.load_controller_config(default_controller="JOINT_POSITION")
AttributeError: module 'robosuite' has no attribute 'load_controller_config'. Did you mean: 'load_part_controller_config'?
```

### Expected behavior

NA

**Comment by handsomelada** [comment]
i have met the same issue
