### ISSUE TITLE
Newer version of Python (3.12) breaks the way that offscreen rendering works

### ISSUE THREAD

**Issue by mishmish66** [ARISE-Initiative/robosuite#569]
### System Info

```Shell
Ubuntu 24.04, Python 3.12
```

### Information

This happens when using offscreen rendering on python 3.12 because of the way that ctypes and PyOpenGL interact. I'll open a PR as I've seen this issue before (https://github.com/google-deepmind/mujoco/issues/1299) and suggested a fix on the mujoco repo, which they took so I'll just make a PR for that here.

The error message is this:

```
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import robosu
KeyboardInterrupt
>>> import robosuite as suite
nv_name="Lift",  # try with other tasks like "Stack" and "Door"
    robots="Panda",  # try with other robots like "Sawyer" and "Jaco"
    has_renderer=False,
    has_offscreen_renderer=True,
    use_camera_obs="RGB",
    use_object_obs=False,
)[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/scripts/setup_macros.py (macros.py:55)
[robosuite WARNING] Could not import robosuite_models. Some robots may not be available. If you want to use these robots, please install robosuite_models from source (https://github.com/ARISE-Initiative/robosuite_models) or through pip install. (__init__.py:30)
[robosuite WARNING] Could not load the mink-based whole-body IK. Make sure you install related import properly, otherwise you will not be able to use the default IK controller setting for GR1 robot. (__init__.py:40)
>>> 
>>> env = suite.make(
...     env_name="Lift",  # try with other tasks like "Stack" and "Door"
...     robots="Panda",  # try with other robots like "Sawyer" and "Jaco"
...     has_renderer=False,
...     has_offscreen_renderer=True,
...     use_camera_obs="RGB",
...     use_object_obs=False,
... )
[robosuite INFO] Loading controller configuration from: /home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/controllers/config/robots/default_panda.json (composite_controller_factory.py:69)
dict_keys([<class 'str'>, <class 'OpenGL._opaque.EGLDeviceEXT_pointer'>, <class 'NoneType'>, <class 'tuple'>])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/base.py", line 41, in make
    return REGISTERED_ENVS[env_name](*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/manipulation/lift.py", line 187, in __init__
    super().__init__(
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/manipulation/manipulation_env.py", line 171, in __init__
    super().__init__(
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/robot_env.py", line 221, in __init__
    super().__init__(
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/base.py", line 158, in __init__
    self._reset_internal()
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/manipulation/lift.py", line 394, in _reset_internal
    super()._reset_internal()
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/robot_env.py", line 519, in _reset_internal
    super()._reset_internal()
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/environments/base.py", line 329, in _reset_internal
    render_context = MjRenderContextOffscreen(self.sim, device_id=self.render_gpu_device_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/utils/binding_utils.py", line 214, in __init__
    super().__init__(sim, offscreen=True, device_id=device_id, max_width=max_width, max_height=max_height)
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/utils/binding_utils.py", line 81, in __init__
    self.gl_ctx = GLContext(max_width=max_width, max_height=max_height, device_id=self.device_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/robosuite/renderers/context/egl_context.py", line 129, in __init__
    EGL.eglChooseConfig(EGL_DISPLAY, EGL_ATTRIBUTES, ctypes.byref(config), config_size, num_configs)
  File "/home/mishmish/venvs/poo/lib/python3.12/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
ctypes.ArgumentError: argument 3: TypeError: No array-type handler for type _ctypes.CArgObject (value: <cparam 'P' (0x7dc1f71d3220)>) registered
>>> 
```

### Reproduction

1. Use python 3.12
2. use offscreen rendering like with the following snippet (at least on my headless machine this breaks it)
```
import robosuite as suite

env = suite.make(
    env_name="Lift",  # try with other tasks like "Stack" and "Door"
    robots="Panda",  # try with other robots like "Sawyer" and "Jaco"
    has_renderer=False,
    has_offscreen_renderer=True,
    use_camera_obs="RGB",
    use_object_obs=False,
)
```

### Expected behavior

I would expect the environment to not crash and render offscreen

**Comment by snasiriany** [comment]
Thanks for letting us know, and thanks for the PR!
